set_xmakever("2.6.3")

add_requires("glm")
add_requires("glad")
add_requires("glfw")

target("GLKit")
    set_kind("static")
    add_files("*.cpp")
    add_headerfiles("**.h")
    add_headerfiles("**.hpp")
    add_includedirs("../")
    set_languages("cxx11")
    add_rules("mode.debug", "mode.release")
    add_packages("glad")
    add_packages("glfw")
    add_packages("glm")