set_xmakever("2.6.3")

includes("../../Foundation/Foundation")
includes("../../KSMediaCodec/KSMediaCodec")
includes("../../KSImage/KSImage")
add_requires("nlohmann_json")
add_requires("spdlog")

target("VideoEditor")
    set_kind("static")
    set_languages("cxx17")
    add_files("src/**.cpp")
    add_headerfiles("include/VideoEditor/**.hpp")
    add_includedirs("include/VideoEditor")
    add_includedirs("include", { interface = true })
    add_rules("mode.debug", "mode.release")
    add_packages("nlohmann_json", { public = true })
    add_packages("spdlog")
    add_deps("Foundation")
    add_deps("KSMediaCodec")
    add_deps("KSImage")