set_xmakever("2.6.3")

includes("../GLKit")
includes("../Core")

add_requires("glm")
add_requires("glad")
add_requires("glfw")
add_requires("rapidjson")
add_requires("spdlog")
add_requires("tclap")

rule("SupportFFmpeg")
    on_load(function (target)
        if os.exists("../Vendor/win32/ffmpeg") == false then
            local oldir = os.cd("../Vendor/win32")
            import("net.http")
            import("utils.archive")
            if os.exists("ffmpeg.zip") == false then
                http.download("https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-02-28-12-32/ffmpeg-n4.3.2-160-gfbb9368226-win64-gpl-shared-4.3.zip", "ffmpeg.zip")
            end
            archive.extract("ffmpeg.zip")
            os.trymv("ffmpeg-n4.3.2-160-gfbb9368226-win64-gpl-shared-4.3", "ffmpeg")
            os.cd(oldir)            
        end    
        target:add("includedirs", "../Vendor/win32/ffmpeg/include")
        target:add("linkdirs", "../Vendor/win32/ffmpeg/lib")
        target:add("links", "avcodec", "avformat", "avutil", "swresample", "swscale")
    end)
    after_build(function (target)
        os.cp("../Vendor/win32/ffmpeg/bin/*.dll", target:targetdir())
    end)

target("CMD")
    set_kind("binary")
    set_languages("cxx11")
    add_files("*.cpp")
    add_includedirs("../")
    add_includedirs("../Vendor/win32/ffmpeg/include")
    add_rules("mode.debug", "mode.release")
    add_rules("SupportFFmpeg")
    add_packages("glad")
    add_packages("glfw")
    add_packages("glm")
    add_packages("rapidjson")
    add_packages("spdlog")
    add_packages("tclap")
    add_deps("GLKit")
    add_deps("Core")